replicaCount: 2

image:
  repository: lrplateng/demo-service:v1.0.0
  pullPolicy: Always

imagePullSecrets:
  - name:
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  class: alb
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}